check if there is a MR open

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -53,6 +53,19 @@ launch_testfirmware:
     - sed -i '/ref:/s#.*#      ref:\ '"$CI_COMMIT_REF_NAME"'#' .gitlab-ci.yml
     - git commit -am "Updating Hog to $CI_COMMIT_REF_NAME"
     - git push origin auto/$CI_COMMIT_REF_NAME
+    # Check if there is already a MR open with the current branch, if not open it
+    - response=$(curl --header "PRIVATE-TOKEN:\ $HOG_PUSH_TOKEN" "https://gitlab.example.com/api/v4/projects/28784308/merge_requests?source_branch=auto/$CI_COMMIT_REF_NAME")
+    - if [ $? -eq 0 ]; then
+      # Check if there are any merge requests in the response
+      if [ $(echo "$response" | jq length) -gt 0 ]; then
+        echo "There is an open merge request with source branch 'auto/$CI_COMMIT_REF_NAME'.";
+        # If you want to extract more information about the MR, you can parse the response here
+        else
+          echo "There are no open merge requests with source branch 'auto/$CI_COMMIT_REF_NAME'. I will open one...";
+        fi;
+      else
+        echo "Failed to retrieve merge requests. Please check your GitLab API endpoint and token.";
+      fi
   interruptible: true
 
 build-doxygen-test:
