open MR

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -54,15 +54,20 @@ launch_testfirmware:
     - git commit -am "Updating Hog to $CI_COMMIT_REF_NAME"
     - git push origin auto/$CI_COMMIT_REF_NAME
     # Check if there is already a MR open with the current branch, if not open it
-    - env
     - response=$(curl --header "PRIVATE-TOKEN:${TF_TOKEN}" "https://gitlab.com/api/v4/projects/28784308/merge_requests?source_branch=auto/$CI_COMMIT_REF_NAME")
-    - echo $response
     - if [ $? -eq 0 ]; then
         if [ $(echo "$response" | jq length) -gt 0 ]; then
           echo "$response" | jq length;
           echo "There is an open merge request with source branch 'auto/$CI_COMMIT_REF_NAME'.";
         else
           echo "There are no open merge requests with source branch 'auto/$CI_COMMIT_REF_NAME'. I will open one...";
+          response_MR=$(curl --request POST --header "PRIVATE-TOKEN:$TF_TOKEN" --header "Content-Type:application/json" --data "{\"source_branch\":\"auto/$CI_COMMIT_REF_NAME\", \"target_branch\":\"develop\", \"title\":\"Automatic MR with Hog branch $CI_COMMIT_REF_NAME\", \"description\":\"\"}" "https://gitlab.com/api/v4/projects/28784308/merge_requests");
+          if [ $? -eq 0 ]; then
+            MR_URL=$(echo "$response" | jq -r '.web_url');
+            echo "Merge request created successfully. URL= $MR_URL";
+          else
+            echo "Failed to create merge request. Please check your GitLab API endpoint and token.";
+          fi;
         fi;
       else
         echo "Failed to retrieve merge requests. Please check your GitLab API endpoint and token.";
