wait on testfirmware pipeline

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -57,8 +57,10 @@ launch_testfirmware:
     - response=$(curl --header "PRIVATE-TOKEN:${TF_TOKEN}" "https://gitlab.com/api/v4/projects/28784308/merge_requests?source_branch=auto/$CI_COMMIT_REF_NAME")
     - if [ $? -eq 0 ]; then
         if [ $(echo "$response" | jq length) -gt 0 ]; then
-          MR_ID=$(echo "$response" | jq -r '.iid');
+          MR_ID=$(echo "$response" | jq .[].iid);
+          MR_URL=$(echo "$response" | jq .[].web_url);
           echo "There is already an open merge request with source branch 'auto/$CI_COMMIT_REF_NAME'.";
+          echo "$MR_URL"
         else
           echo "There are no open merge requests with source branch 'auto/$CI_COMMIT_REF_NAME'. I will open one...";
           response_MR=$(curl --request POST --header "PRIVATE-TOKEN:$TF_TOKEN" --header "Content-Type:application/json" --data "{\"source_branch\":\"auto/$CI_COMMIT_REF_NAME\", \"target_branch\":\"develop\", \"title\":\"Automatic MR with Hog branch $CI_COMMIT_REF_NAME\", \"description\":\"\"}" "https://gitlab.com/api/v4/projects/28784308/merge_requests");
@@ -75,7 +77,22 @@ launch_testfirmware:
         echo "Failed to retrieve merge requests. Please check your GitLab API endpoint and token.";
         exit 1;
       fi;
-    - curl -X GET "https://gitlab.com/api/v4/projects/28784308/pipelines?merge_request_iid=$MR_ID" --header "Private-Token:$TF_TOKEN"
+    - sleep 10s
+    - pileline_status="running"
+    - while [ $pipeline_status == "running" ]; do
+        pipeline_response=$(curl -X GET "https://gitlab.com/api/v4/projects/28784308/pipelines?merge_request_iid=$MR_ID" --header "Private-Token:$TF_TOKEN")
+        pipeline_status=$(echo $pipeline_response | jq .[0].status);
+        pipeline_url=$(echo $pipeline_response | jq .[0].web_url);
+      done
+    - if [ $pipeline_status == "failed"]; then
+        echo "TestFirmware pipeline failed. $pipeline_url";
+        exit 1;
+      elif [ $pipeline_status == "success"]; then 
+        echo "TestFirmware pipeline was successful!";
+      else 
+        echo "TestFirmware pipeline status unknown... Exiting!";
+        exit 1;
+      fi;
   interruptible: true
 
 build-doxygen-test:
