Logger working

diff --git a/Do b/Do
--- a/Do
+++ b/Do
@@ -2,19 +2,15 @@
 # Array of IDE executables, the paths where tclsh is located wrt to them, and the tclsh executable name.
 # The separator must be comma and space and the path separator in the second element must be : with no spaces
 . $(dirname "$0")/Other/CommonFunctions.sh
-msg_counter init
-DEBUG_VERBOSE=5
-ROOT_PROJECT_FOLDER=$(pwd)
-LOG_INFO_FILE=$ROOT_PROJECT_FOLDER"/hog_info.log"
-LOG_WAR_ERR_FILE=$ROOT_PROJECT_FOLDER"/hog_warning_errors.log"
-#  if [[ -n "$HOG_COLORED" ]]; then
-#     new_print_hog "$(dirname "$0")"
-#   else
-#     print_hog "$(dirname "$0")"
-#   fi
-  if [[ -n $HOG_LOGGER ]]; then
+if [[ -v HOG_LOGGER && $HOG_LOGGER == ENABLED ]]; then
+    msg_counter init
+    DEBUG_VERBOSE=5
+    ROOT_PROJECT_FOLDER=$(pwd)
+    LOG_INFO_FILE=$ROOT_PROJECT_FOLDER"/hog_info.log"
+    LOG_WAR_ERR_FILE=$ROOT_PROJECT_FOLDER"/hog_warning_errors.log"
     Logger_Init "$*"
-  fi
+fi
+
 
 executables=(
     "tclsh, ., tclsh"
@@ -71,15 +67,16 @@ for executable in "${executables[@]}"; do
 done
 
 if [ "$found" == 1 ]; then
-    Logger $executable_path $hog_dir/Tcl/launch.tcl "$@"
-    # exit $?
-    Hog_exit
+  if [[ -v HOG_LOGGER && $HOG_LOGGER == ENABLED ]]; then
+      Logger $executable_path $hog_dir/Tcl/launch.tcl "$@"
+      Hog_exit
+  else
+      $executable_path $hog_dir/Tcl/launch.tcl "$@"
+      exit $?
+  fi
+    
 else
     echo "Error: No IDE exectuable found in PATH. You need an IDE in your PATH to use Hog." >&2
     exit 1
 fi
-
-
-
-
 
