adding all the stages back

diff --git a/hog-dynamic.yml b/hog-dynamic.yml
--- a/hog-dynamic.yml
+++ b/hog-dynamic.yml
@@ -56,3 +56,134 @@ merge_and_tag:
        paths:
          - $CI_PROJECT_DIR/VivadoProject/$PROJECT_NAME
        expire_in: 30 day
+
+.simulate_project: &simulate_project
+     <<: *only-default
+     stage: simulation
+     variables:
+        <<: *vars
+     script:
+      - "if [ -z ${HOG_SIMULATION_LIB_PATH+x} ]; then echo 'Simulation library path is not defined'; else vivado -mode batch -notrace -source ./Hog/Tcl/launchers/launch_simulation.tcl -tclargs -lib_path $HOG_SIMULATION_LIB_PATH $PROJECT_NAME ; fi"
+     artifacts:
+       name: simulation_files
+       paths:
+         - $CI_PROJECT_DIR/VivadoProject/$PROJECT_NAME/$PROJECT_NAME.sim
+       expire_in: 30 day
+     allow_failure: true
+
+.synthesise_ips: &synthesise_ips
+    <<: *only-default
+    stage: ip
+    variables:
+        <<: *vars
+    script:
+        - until echo $HOG_PASSWORD | kinit $HOG_USER ; do echo "Retrying"; sleep 2; done
+        - if [ -z ${HOG_IP_NJOBS+x} ]; then export HOG_IP_NJOBS=4; fi
+        - "if [ -z ${HOG_IP_EOS_PATH+x} ]; then
+           echo 'No EOS path for IPs defined';
+           vivado -mode batch -notrace -source ./Hog/Tcl/launchers/launch_ip_synth.tcl -tclargs -NJOBS $HOG_IP_NJOBS $PROJECT_NAME ;
+           else vivado -mode batch -notrace -source ./Hog/Tcl/utils/get_ips.tcl -tclargs -eos_ip_path \"$HOG_IP_EOS_PATH\" $PROJECT_NAME;
+            vivado -mode batch -notrace -source ./Hog/Tcl/launchers/launch_ip_synth.tcl -tclargs -NJOBS $HOG_IP_NJOBS -eos_ip_path \"$HOG_IP_EOS_PATH\" $PROJECT_NAME ;
+          fi"
+        - "rm BD/*.bd ||:"
+
+    artifacts:
+        name: vivado_runs
+        paths:
+            - $CI_PROJECT_DIR/VivadoProject/$PROJECT_NAME
+            - $CI_PROJECT_DIR/IP
+            - $CI_PROJECT_DIR/BD
+        expire_in: 30 day
+
+.synthesise_project: &synthesise_project
+    <<: *only-default
+    stage: synthesis
+    variables:
+        <<: *vars
+    script:
+        - if [ -z ${HOG_NJOBS+x} ]; then export HOG_NJOBS=4; fi
+        - vivado -mode batch -notrace -source ./Hog/Tcl/launchers/launch_synthesis.tcl -tclargs -NJOBS $HOG_NJOBS $PROJECT_NAME
+    artifacts:
+        name: vivado_synth
+        paths:
+            - $CI_PROJECT_DIR/VivadoProject/$PROJECT_NAME
+            - $CI_PROJECT_DIR/bin
+            - $CI_PROJECT_DIR/IP
+            - $CI_PROJECT_DIR/BD
+        expire_in: 30 day
+
+.implement_project: &implement_project
+    <<: *only-default
+    stage: implementation
+    variables:
+        <<: *vars
+    script:
+        - git status
+        - git diff
+        - if [ -z ${HOG_NJOBS+x} ]; then export HOG_NJOBS=4; fi
+        - if [ -z ${HOG_NO_BITSTREAM+x} ]; then export HOG_NO_BITSTREAM=0; fi
+        - "if [ $HOG_NO_BITSTREAM == '1' ]; then
+           vivado -mode batch -notrace -source ./Hog/Tcl/launchers/launch_implementation.tcl -tclargs -no_bitstream -NJOBS $HOG_NJOBS  $PROJECT_NAME;
+           else vivado -mode batch -notrace -source ./Hog/Tcl/launchers/launch_implementation.tcl -tclargs -NJOBS $HOG_NJOBS $PROJECT_NAME;
+           fi"
+        - "cat $CI_PROJECT_DIR/bin/$PROJECT_NAME*/versions* $CI_PROJECT_DIR/bin/$PROJECT_NAME*/timing_* > note.md"
+        - ./Hog/Other/WriteGitlabNote.sh $HOG_PUSH_TOKEN $CI_API_V4_URL $CI_PROJECT_ID $CI_MERGE_REQUEST_IID note.md
+
+    artifacts:
+        name: implementation_and_bitfiles
+        paths:
+            - $CI_PROJECT_DIR/VivadoProject/$PROJECT_NAME
+            - $CI_PROJECT_DIR/bin
+        expire_in: 1 month
+
+collect_artifacts:
+    <<: *only-default
+    stage: collect
+    variables:
+        <<: *vars
+    script:
+        - "printf \"## Repository info\n- Merge request number: $CI_MERGE_REQUEST_IID\n- Branch name: $CI_COMMIT_REF_SLUG\n\n\" > $CI_PROJECT_DIR/bin/note.md"
+        - ./Hog/Other/Changelog.sh $CI_MERGE_REQUEST_TARGET_BRANCH_NAME >> $CI_PROJECT_DIR/bin/note.md
+        - files=$(shopt -s nullglob dotglob; echo $CI_PROJECT_DIR/bin/*/*.txt)
+        - "if (( ${#files} )); then
+          cat $CI_PROJECT_DIR/bin/*/*.txt >> $CI_PROJECT_DIR/bin/note.md;
+          fi"
+        - git fetch origin refs/notes/*:refs/notes/*
+        - git notes add -fm "$CI_MERGE_REQUEST_IID $CI_COMMIT_REF_SLUG"
+        - git push origin refs/notes/*
+        - "if [ -e $CI_PROJECT_DIR/bin/ -a -n '$HOG_UNOFFICIAL_BIN_EOS_PATH' ]; then until echo $HOG_PASSWORD | kinit $HOG_USER ; do echo Retrying; sleep 2; done;
+          eos mkdir -p $HOG_UNOFFICIAL_BIN_EOS_PATH/$CI_COMMIT_SHORT_SHA;
+          eos cp -r $CI_PROJECT_DIR/bin/* $HOG_UNOFFICIAL_BIN_EOS_PATH/$CI_COMMIT_SHORT_SHA; fi"
+
+    artifacts:
+        name: all_projects
+        paths:
+            - $CI_PROJECT_DIR/bin
+        expire_in: 10 years
+    allow_failure: true
+
+
+make_doxygen:
+    <<: *only-default
+    only:
+      variables:
+        - $HOG_USE_DOXYGEN == "1"
+    stage: doxygen
+    variables:
+        <<: *vars
+    script:
+        - until echo $HOG_PASSWORD | kinit $HOG_USER ; do echo Retrying; sleep 2; done
+        - vivado -mode batch -notrace -source ./Hog/Tcl/utils/make_doxygen.tcl
+        - DESCRIBE=$(git describe --always --tags --long)
+        - "if [ -e $CI_PROJECT_DIR/Doc/html -a -n '$HOG_UNOFFICIAL_BIN_EOS_PATH' ]; then
+          eos mkdir -p $HOG_UNOFFICIAL_BIN_EOS_PATH/$CI_COMMIT_SHORT_SHA/Doc-$DESCRIBE;
+          eos cp -r ./Doc/html/* $HOG_UNOFFICIAL_BIN_EOS_PATH/$CI_COMMIT_SHORT_SHA/Doc-$DESCRIBE;
+          elif [ -e $CI_PROJECT_DIR/Doc/html ]; then echo \"Environmental variable HOG_UNOFFICIAL_BIN_EOS_PATH not set. Doxygen documentation cannot be copied to eos.\";
+          else echo \"Documentation not found in $CI_PROJECT_DIR/Doc/html\"; fi"
+    artifacts:
+        name: docs
+        paths:
+            - $CI_PROJECT_DIR/Doc
+        expire_in: 10 years
+    dependencies: []
+    allow_failure: true
